twitter_user_list:
  - "fomosaurus"
  - "CryptoGrills"
  - "Darrenlautf"
  - "smallcapscience"
  - "cryptodetweiler"
  - "notEezzy"
  - "blknoiz06"
  - "dcfgod"
  - "nosleepjon"
  - "thegreenbutton_"
  - "rewkang"
telegram_user_list:
  - -504043770
twitter_api_key: ""
twitter_api_key_secret: ""
twitter_access_token: ""
twitter_access_token_secret: ""
telegram_token: ""
loop_time: 900
