twitter_user_list:
  - "fomosaurus"
  - "chatwithcharles"
  - "CryptoSpider1"
  - "CryptoGrills"
  - "CryptoMaestro"
  - "N2ckchong"
  - "Darrenlautf"
  - "George_harrap"
  - "solanians_"
telegram_user_list:
  - -504043770
twitter_api_key: ""
twitter_api_key_secret: ""
twitter_access_token: ""
twitter_access_token_secret: ""
telegram_token: ""
loop_time: 900
